title: "Dinuka McKenzie"
description: "Award-winning Australian crime fiction author"
url: ""
baseurl: ""
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - tina
  - netlify.toml
  - README.md
  - package.json
  - node_modules

# Prevent Jekyll processing these files
keep_files:
  - admin
  - signup.html
  - login.html
