[build]
  command = "npm install tinacms @tinacms/cli && bundle exec jekyll build && NODE_OPTIONS=--max-old-space-size=4096 npx @tinacms/cli@latest build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.0"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
